### ISSUE TITLE
Propose "org.tempel.paths-file" for UTI

### ISSUE THREAD

**Issue by siegel** [tempelmann/DotPathsFileSpec#1]
You wrote:
> For the UTI name itself, I like to come up with something that's not bound to anyone's own domain. Ideally, we'd register one with Apple under "public." but that's unlikely to happen.

Indeed so. And further, I would counsel against using `public.` or trying to invent a new top-level domain for your UTI.

I suggest that the `.paths` file content type be based on something that reflects its origin.

Perhaps `org.tempel.paths-file` would work? That doesn't make it proprietary at all, since you can still register it (if there is a registry anywhere) and promulgate it.

For example: Markdown's public UTI is `net.daringfireball.markdown`. Java source code is `com.sun.java-source`. So there's precedent for doing it this way.

**Comment by tempelmann** [comment]
Sun and Daringfireball have a right to call this their own. This, however, is more a public and open effort and while I may have instigated it, I don't want to take all the credit for it. Also, competitors may be more hesitant to adopt it if it explicitly refers to me and my product.

That's why I rather come up with a non-specific top-level domain such as "common.". Unless you like to give you domain name for this? I'm sure no one would have a problem with that ;)

Also note my recent update on the UTI section. There should be a basic UTI that describes the semantics, such as "common.paths-file" and a specific one for the implementation and format (LF or NUL as line seps, each line being a posix path). So, we'll probably need two names.

Huh, I can't just comment but can only "close with comment". Simply reply, and I'm sure it'll reopen.

**Comment by siegel** [comment]
> Sun and Daringfireball have a right to call this their own. This, however, is more a public and open effort and while I may have instigated it, I don't want to take all the credit for it. Also, competitors may be more hesitant to adopt it if it explicitly refers to me and my product.

You have a right to call this your own, too. :-) However: it's not about "taking credit", it's about the origin and provenance, not about whether it's publicly documented, collaboratively enhanced, or anything else. You invented it, that's where it came from, that's the reality.

And if competitors are hesitant about adopting the file format because of the ordering of a few ASCII characters in the type identifier,  that's on them. It's a useful file format, and people who can't get past that will lose out.

Apple's recommendation about naming:

> Your UTI string must be unique. Following the reverse-DNS format beginning with com.companyName is a simple way to ensure uniqueness. While the system can support different UTI strings with the same specification, the reverse is not true.

`org.tempel.*` is just as valid (or you could use `com.tempel.*` but you already use `org.tempel.` in your products, so there's precedent).

If there's a `common.` TLD for UTIs, there's precedent for using that, but `common.paths-file` has a high risk of not being unique. If you insist on the TLD being `common`, I would suggest at least `common.tempel.paths-file`.

> Also note my recent update on the UTI section. There should be a basic UTI that describes the semantics, such as "common.paths-file" and a specific one for the implementation and format (LF or NUL as line seps, each line being a posix path). So, we'll probably need two names.

I recommend against this, unless you're _also_ going to introduce distinct filename extensions for each distinct format. Otherwise there's no way to tell at runtime which a file is from its metadata alone, and the extra types just add a layer of complexity and create a conflict for applications that import (or export) that type declaration.

(For that matter, distinguishing between each file format based on its filename extension would not actually help in some of my use cases, although in other cases it would save the time of having to examine the file to figure out what the record delimiter is.)

**Comment by tempelmann** [comment]
I have now registered the "utis.cc" domain. So we can now vote on the UTI:

- cc.utis.paths
- cc.utis.posix-paths
- cc.utis.file-paths
- cc.utis.paths-file

**Comment by siegel** [comment]
Insofar as I have a preference at all :-) I think I'd lean toward `cc.utis.paths-file`.

**Comment by tempelmann** [comment]
If "utis.cc" would ever be open to defining more UTIs (which I don't object to), then adding "-file"
makes sense, indeed.

Or even use something like "cc.utis.files.paths". But that's overkill again, for now.

So, "cc.utis.paths-file" is it!
